### PR TITLE
Proposal: Frequency Capping

### PR DESCRIPTION
**Pull request by dreischer**
Proposal to implement a cookie-less and privacy-friendly frequency capping solution in Prebid

### CODE REVIEW

**Review by bretg — APPROVED** [review]

**Comment by bretg** [comment]
@dreischer - there's an aspect of fcaps that seems to be missing here -- the signal to back to the DSP covering which campaign(s) have reached their cap.

Without that signal, DSPs may bid fruitlessly with a campaign that's destined to be capped when they would have chosen a different one had they known.

**Comment by GLStephen** [comment]
@bretg does that signal path exist in a formalized state?

**Comment by bretg** [comment]
Not that I know of. Perhaps that's something proposal ought to outline?

**Comment by epouradier** [comment]
@dreischer Thanks for the proposal. A few questions/feedback:
1- In identity based solution with "Decryption key for trusted parties", is it realistic considering that, as you said, "This would require a unique bid-request to be created for each DSP" and that there are most of the time intermediaries between the publisher and the DSP?
2- For identity-less solution, since the DSP can run an advertiser campaign and buy inventory through multiple SSPs potentially connected to a publisher through header bidding wrapper/server, the frequency capping would have to be managed at this level (header bidding wrapper/server) and not at the SSP level.

**Pull request merged**
